version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    commands:
#      - mvn test
#      - mvn clean install
      - echo Building Docker image
      - docker build --build-arg COGNITO_REGION=$REGION --build-arg USER_POOL=$USER_POOL --build-arg CLIENT_ID=$CLIENT_ID --build-arg ACCESS_KEY=$ACCESS_KEY --build-arg SECRET_KEY=$SECRET_KEY  -t johnnie3000/backend:v0 .
      - docker push docker.io/johnnie3000/backend:v0

  post_build:
    commands:
#      - mvn verify
      - echo Build completed on `date`