version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub as $DOCKERHUB_USERNAME
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - mvn clean
  build:
    commands:
      - mvn package

  post_build:
    commands:
      # Uncomment if necessary
      # - mvn verify
      - echo "Build completed on $(date)"

